### ISSUE TITLE
Converter os show notes para usar a diretiva top5

### ISSUE THREAD

**Issue by elyezer** [CastalioPodcast/castaliopodcast.github.io#163]
No último episódio publicado foi adicionada a diretiva `top5` que permite centralizar os items recomendados no Top 5 e também contar quantas vezes um item específico foi recomendado. Isso foi adicionado com o PR #158.

Já no PR #161, foi criada uma nova diretiva que permitiu criar a página com os items mais recomendados (veja em https://castalio.info/top5.html). Basicamente essa diretiva usa informações da diretiva `top5` e cria um ranking dos items mais recomendados.

No PR #162 o arquivo geral com os items do Top 5 foi atualizado e deve prover quase tudo que foi mencionado nos show notes, o que vai facilitar converter todos os show notes para usar a diretiva `top5`. Também no #142, 5 show notes foram convertidos para usar a nova diretiva, ele serve de exemplo para converter os demais show notes.

Essa issue tem como objetivo capturar o que ainda falta ser convertido e possibilita que mais de uma pessoa contribua com a conversão. Se você pretende ajudar com a conversão, deixa um comentário nessa issue dizendo qual o episódio ou os episódios você pretende converter, dessa forma evitamos trabalho duplicado.

A checklist abaixo mostra o que já foi convertido e revisado e o que falta ser convertido ou revisado:

- [x] 001-og-maciel.rst (#171)
- [x] 002-karlisson-bezerra-ilustrador.rst (#171)
- [x] 003-kurtkraut.rst (#171)
- [x] 004-luciana-fujii-pontelo-gnome-women-outreach-program.rst (#171)
- [x] 005-murilo-queiroz-em-busca-dos-tesouros.rst (#171)
- [x] 006-diego-burigo-zacarao-projeto-transifex.rst
- [x] 007-frederico-goncalves-guimaraes-software-livre-educacional.rst
- [x] 008-yuri-malheiros-engenharia-de-software-e-inteligencia-artificial.rst
- [x] 009-johan-dahlin-stoq-gestor-comercial-livre.rst
- [x] 010-lucas-rocha-the-board-parte-1.rst
- [x] 011-lucas-rocha-the-board-parte-2.rst
- [x] 012-igor-pires-soares-projeto-fedora.rst
- [x] 013-aline-duarte-bessa-accerciser.rst
- [x] 014-hugo-doria-arch-linux.rst
- [x] 015-carlos-ribeiro-radiotray.rst
- [x] 016-alvaro-turicas-justen-arduino.rst
- [x] 017-pete-savage-git-in-the-trenches-gitt.rst
- [x] 018-augusto-campos-br-linux-br-mac-efetividade.rst
- [x] 019-evandro-pastor-quarto-estudio.rst
- [x] 020-guilherme-salgado-canonical-e-linaro.rst
- [x] 021-especial-andre-gondim-ubuntu-brasil.rst
- [x] 022-alexandre-coster-asobo-studio.rst
- [x] 023-elvis-pfutzenreuter-conectiva-linux.rst
- [x] 024-ruda-moura-conectiva-linux.rst
- [x] 025-joao-fernando-costa-junior-revista-espirito-livre.rst
- [x] 026-rodrigo-novo-conectiva-linux.rst
- [x] 027-rodrigo-padula-de-oliveira-ufrj.rst
- [x] 028-marcelo-hashimoto-polly-twitter-client.rst
- [x] 029-ana-cristina-fricke-matte-text-livre.rst
- [x] 030-rodrigo-belem-ubuntu-brasil.rst
- [x] 031-ivan-brasil-fuzzer-ubuntero.rst
- [x] 032-gabriel-falcao-yipit.rst
- [x] 033-henrique-bastos-welcome-to-the-django.rst
- [x] 034-julio-monteiro-jobscore.rst
- [x] 035-fabio-kung-e-pedro-belo-heroku.rst
- [x] 036-caike-souza-envy-labs.rst
- [x] 037-flavio-ribeiro-globo-com.rst
- [x] 038-felipe-ribeiro-spotify.rst
- [x] 039-djavan-fagundes-gnome-brasil.rst
- [x] 040-danilo-resende-facebook.rst
- [x] 041-fabio-nogueira-ubuntu-brasil.rst
- [x] 042-cristiano-costa-hora-do-mac.rst
- [x] 043-felipe-borges-google-summer-of-code.rst
- [x] 044-bruno-goncalves-biglinux.rst
- [x] 045-licio-fonseca-google.rst
- [x] 046-carlos-brando-e-rafael-rosa-fu-grokpodcast-part-1.rst
- [x] 047-carlos-brando-e-rafael-rosa-fu-grokpodcast-part-2.rst
- [x] 048-julian-fernandes-ubuntu-br-sc.rst
- [x] 049-fabiano-fidencio-red-hat.rst
- [x] 050-luciano-ramalho-oficinas-turing.rst
- [x] 051-edicao-de-2-anos-og-maciel-red-hat.rst
- [x] 052-alexandre-gaigalas-yahoo.rst
- [x] 053-everaldo-canuto-toca-do-canuto.rst
- [x] 054-enrico-nicoletto-rafael-ferreira-projeto-gnome.rst
- [x] 055-editor-vim.rst
- [x] 056-splinter.rst
- [x] 057-natal-parte-1.rst
- [x] 058-natal-parte-2.rst
- [x] 059-natal-parte-3.rst
- [x] 060-andrews-medina-splinter.rst
- [x] 061-humberto-zanetti-smart-braille.rst
- [x] 062-diego-rodrigo-santos-sobrecervejas.rst
- [x] 063-thiago-avelino-vim-bootstrap.rst
- [x] 064-thiago-avelino-openmining.rst
- [x] 065-gustavo-barbieri-enlightenment-profusion.rst
- [x] 066-thiago-perrotta-leitura-e-tecnolocia.rst
- [x] 067-aurelio-jargas-conectiva-livros.rst
- [x] 068-aurelio-jargas-projetos.rst
- [x] 069-renzo-nucciteli-python-brasil.rst
- [x] 070-bruno-rocha-flask-veganismo.rst
- [x] 071-bruno-quokka-cms.rst
- [x] 072-eduardo-matos-puchdb-quadrinhos.rst
- [x] 073-python-brasil-12-parte-1.rst
- [x] 074-python-brasil-12-parte-2.rst
- [x] 075-python-brasil-12-parte-3.rst
- [x] 076-book-review-python-packages.rst
- [x] 077-practical-vim-e-novidades-da-semana.rst
- [x] 078-gabriel-engel-rocket-chat.rst
- [x] 079-paula-grangeiro.rst
- [x] 080-kenneth-reitz.rst
- [x] 081-as-vinhas-da-ira-e-novidades-da-semana.rst
- [x] 082-book-reviews-e-novidades-da-semana.rst
- [x] 083-tarek-ziade.rst
- [x] 084-tech-news-e-book-review.rst
- [x] 085-arx-cruz.rst
- [x] 086-linguagem-go-parte-1.rst
- [x] 087-linguagem-go-parte-2.rst
- [x] 088-episodio-especial-de-6-anos.rst
- [x] 089-tech-news-e-book-review.rst
- [x] 090-empreender-e-programar-parte-1.rst
- [x] 091-empreender-e-programar-parte-2.rst
- [x] 092-linguagem-lua-parte-1.rst
- [x] 093-linguagem-lua-parte-2.rst
- [x] 094-tech-news.rst
- [x] 095-plataforma-microsoft-parte-1.rst
- [x] 096-plataforma-microsoft-parte-2.rst
- [x] 097-vladimir-melo.rst
- [x] 098-rodolpho-eckhardt.rst
- [x] 099-tech-news-e-book-review.rst
- [x] 100-cage-match-de-sistemas-operacionais.rst (#172)
- [x] 101-automatizacao-de-interface-web-com-selenium.rst (#172)
- [x] 102-marcelo-mello.rst (#172)
- [x] 103-linguagem-elixir.rst (#172)
- [x] 104-caipyra-2017.rst (#172)
- [x] 105-loiane-groner.rst (#172)
- [x] 106-dan-bader.rst (#172)
- [x] 107-chat-bots.rst (#172)
- [x] 108-data-science-e-machine-learning.rst (#172)
- [x] 109-jeferson-noronha.rst (#172)
- [x] 110-willian-molinari.rst (#165)
- [x] 111-multimedia-no-linux-parte-1.rst (#172)
- [x] 112-waldirio-pinheiro-spacewalk.rst (#172)
- [x] 113-multimedia-no-linux-part-2.rst (#172)
- [x] 114-mariatta-wijaya-cpython.rst (#172)
- [x] 115-multimedia-no-linux-part-3.rst (#172)
- [x] 116-tech-news.rst (#172)
- [x] 117-engenharia-de-qualidade-101.rst (#172)
- [x] 118-jefferson-rocha-emmi-linux.rst (#172)
- [x] 119-rust-language-with-carol-nichols.rst (#172)
- [x] 120-ambiente-de-desenvolvimento-parte1.rst (#172)
- [x] 121-eduardo-cuducos-linguagem-elm.rst
- [x] 122-python-brasil-13.rst
- [x] 123-ambiente-de-desenvolvimento-parte2.rst
- [x] 124-serverless.rst
- [x] 125-pytest.rst
- [x] 126-john-roa-pycon-colombia.rst
- [x] 127-grupy-sp-regis-santos.rst
- [x] 128-7-anos-og-maciel.rst
- [x] 129-cybelle-oliveira.rst
- [x] 130-ligia-zeppelini-e-commerce.rst (@luckdomingues)
- [x] 131-justin-keyes-neovim.rst (@luckdomingues)
- [x] 132-tulio-faria-react-js.rst (@luckdomingues)
- [x] 133-everton-melo-criptomoedas.rst (@luckdomingues)
- [x] 134-rodrigo-senra-jupter-notebooks.rst (@luckdomingues)
- [x] 135-fernando-masanori-ensino-de-python-ao-redor-do-mundo.rst (#164)
- [x] 136-pizza-de-dados.rst (#164)
- [x] 137-vicente-marcal-filosofia-com-python.rst (#164)
- [x] 138-ana-paula-gomes-qualidade-de-software.rst (#162)
- [x] 139-elcio-ferreira-padroes-e-desenvolvimento-web.rst (#162)
- [x] 140-eduardo-mendes-live-de-python.rst (#162)
- [x] 141-george-guimaraes-code-review.rst (#162)
- [x] 142-david-kopec-classic-computer-science-problems-in-python.rst (#162)
- [x] 143-victor-dias-universo-programado.rst (#158)

**Comment by luckdomingues** [comment]
Bom dia man, vi a tua chamada no twitter, me fala qual o processo para ajudar. Vamos fazer um teste com o " 055-editor-vim.rst" e se eu conseguir desenrolar te mando uma nova lista.

**Comment by elyezer** [comment]
@luckdomingues muito obrigado pelo interesse. O episódio que você mencionou não tem a sessão Top 5 então esse pode ser considerado como já feito. Eu recomendaria algum entre o 102 e 135 a maioria deles são entrevistas e tem a sessão Top 5.

Pegando um como exemplo aqui, vamos com o https://github.com/CastalioPodcast/castaliopodcast.github.io/blob/pelican/content/episodes/110-willian-molinari.rst

Se você abrir o arquivo no seu editor você vai ver algo como:

```rst
Top 5
-----

* **Música:** `Pantera - Mouth of War <https://www.last.fm/pt/music/Pantera/_/Mouth+for+War>`_
* **Música:** `Black Label Society - Demise of Sanity <https://www.last.fm/pt/music/Black+Label+Society/1919+Eternal/Demise+Of+Sanity>`_
* **Música:** `Mega Driver <https://www.last.fm/music/Megadriver>`_
* **Música:** `Andy McKee <https://www.last.fm/pt/music/Andy+McKee>`_
* **Música:** `Jon Gomm <https://www.last.fm/music/Jon+Gomm>`_
* **Filme:** `Mr. Robot <http://www.imdb.com/title/tt4158110/>`_
* **Filme:** `Senhor dos Anéis <http://www.imdb.com/title/tt0120737/>`_
* **Filme:** `Watchmen <http://www.imdb.com/title/tt0409459/>`_
* **Filme:** `Game of Thrones <http://www.imdb.com/title/tt0944947/>`_
* **Filme:** `Sherlock BBC <www.imdb.com/title/tt1475582>`_
* **Filme:** `House of cards <http://www.imdb.com/title/tt1856010/>`_
* **Livro:** `J.R.R Tolkien <http://www.goodreads.com/author/show/656983.J_R_R_Tolkien>`_
* **Livro:** `Deep Work <https://www.goodreads.com/book/show/25744928-deep-work>`_
* **Livro:** `Mastery <http://www.goodreads.com/book/show/13589182-mastery>`_
* **Livro:** `The Pragmatic Programmer <http://www.goodreads.com/book/show/4099.The_Pragmatic_Programmer>`_
* **Livro:** `O Restaurante no fim do universo <http://www.goodreads.com/book/show/10021253-o-restaurante-no-fim-do-universo>`_
```

Aí você trocaria por algo como:

```rst
.. top5::

    :music:
        * Pantera - Mouth of War
        * Black Label Society - Demise of Sanity
        * Mega Driver
        * Andy McKee
        * Jon Gomm
    :movie:
        * Mr. Robot
        * Senhor dos Anéis
        * Watchmen
        * Game of Thrones
        * Sherlock BBC
        * House of cards
    :book:
        * J.R.R Tolkien
        * Deep Work
        * Mastery
        * The Pragmatic Programmer
        * O Restaurante no fim do universo
```

Observe que a linha em branco entre a primeira e terceira linha são importantes. Alguns episódios não tem o link inline como no exemplo que coloquei, aí seria algo como nesse aqui: https://github.com/CastalioPodcast/castaliopodcast.github.io/pull/162/files#diff-e2dd906957478424d1abe420ce03c4b0.

Eu aproveitei e criei o PR com o exemplo acima caso queira dar uma olhada https://github.com/CastalioPodcast/castaliopodcast.github.io/pull/165

**Comment by luckdomingues** [comment]
@elyezer escolhe um e me diz q faço um teste. fico no aguardo. #tamojunto

**Comment by elyezer** [comment]
@luckdomingues pode ser algum entre o 130-134, talvez o 134? Antes de mandar o PR tenha certeza de estar cadastrado no https://hacktoberfest.digitalocean.com para poder contabilizar o PR para vc. Muito obrigado

**Comment by luckdomingues** [comment]
@elyezer , é obrigatório para o envio estar cadastrado no hacktoberfest?

**Comment by luckdomingues** [comment]
@elyezer , como ninguém reclamou de nada do q fiz no 134, então estou pegando do 130 ao 133. Segue o plano. ok ?

**Comment by luckdomingues** [comment]
@elyezer , outra duvida, o que é preciso para resolver isso??? 
![image](https://user-images.githubusercontent.com/20491481/67147747-04101d00-f26e-11e9-8ee0-e4b2ec64897b.png)

**Comment by luckdomingues** [comment]
> @elyezer , como ninguém reclamou de nada do q fiz no 134, então estou pegando do 130 ao 133. Segue o plano. ok ?

Fiz do 130 ao 134 ! :)

**Comment by elyezer** [comment]
@luckdomingues eu comentei nos PRs para resolver os conflitos mas vou colocar aqui o que normalmente faço:

Quando crio meu fork no github normalmente faço um `git clone <url>` e com isso tenho o meu fork e eu consigo fazer as mudanças e mandar os PRs. Para evitar conflito é bom, sempre que for mandar um PR, fazer um rebase dos nossos branches locais em cima do branch em desenvolvimento (aqui seria o `pelican`). Para fazer isso primeiro eu adiciono um novo remote:

```
git remote add upstream https://github.com/CastalioPodcast/castaliopodcast.github.io.git
```

Dessa forma eu consigo buscas as últimas mudanças fazendo um:

```
git fetch upstream
```

Agora que tenho as mudanças mais recentes eu consigo fazer o rebase, para isso primeiro vou ao branch que quero atualizar, depois faço o rebase e mando as mudanças:

```
git checkout <nome-branch>
git rebase upstream/devel
git push -f origin <nome-branch>
```

Vale ressaltar que o `git push -f` no último comando vai sobrescrever o branch remoto então tenha certeza que esta usando o `<nome-branch>` certo. Considerando o seguinte branch `conversao-top5-episode-133` os comandos seriam assim:

```
git fetch upstream
git checkout conversao-top5-episode-133
git rebase upstream/devel
git push -f origin conversao-top5-episode-133
```

Uma dica para evitar ter que fazer rebase muitas vezes seria toda vez que for criar um branch, fazer um fetch no upstream e criar o branch assim:

```
git checkout -b <nome-do-novo-branch> upstream/<branch-devel-no-upstream>
```

Dessa forma você cria um branch que já esta com o rebase feito em cima do branch destino no upstream. O que aconteceu com os seus PRs foi que você modificou um episódio, fez o commit, e depois criou o branch sem especificar o branch base então o git por padrão pega o branch atual se vc olhar na lista de commits do PR #170 (https://github.com/CastalioPodcast/castaliopodcast.github.io/pull/170/commits) você vai ver que ele inclui todos os commits que você fez anteriormente. O ideal nesse caso seria ter apenas um commit em cada PR, dessa forma você evita conflitos.

Caso alguma coisa não tenha ficado claro me fala que tento colocar mais exemplos ou explicar melhor.

**Comment by HigorMonteiro** [comment]
@elyezer gostária de contribuir inicialmente com 007, 008 e 009 :)

**Comment by HigorMonteiro** [comment]
@elyezer acabei ficando empolgado e fiz os show notes do 007 a 017 ;)

**Comment by luckdomingues** [comment]
@elyezer , reserva do 121 ao 129 agora

**Comment by elyezer** [comment]
@luckdomingues durante o fim de semana tivemos algum PRs e agora tudo do 100 ao 143 estão completos. Eu atualizei a lista da descrição com o que já está feito. Nem todos que faltam tem o top 5 então estou tentando passar por eles e já ir marcando.

**Comment by HigorMonteiro** [comment]
@elyezer o checklist está atualizado?

**Comment by elyezer** [comment]
@HigorMonteiro esta sim, estou trabalhando nos 20-29 atualmente.

**Comment by elyssonmr** [comment]
Vou trabalhar no 31 ao 40 :)

**Comment by elyezer** [comment]
Com o commit f98a1f20fe02cdd6aaf01d5cfa66799d072359dd a conversao esta agora completa.
